### ISSUE TITLE
KZTierMapchooser links to gokz forums

### ISSUE THREAD

**Issue by jvnipers** [KZGlobalTeam/docs#13]
https://github.com/KZGlobalTeam/docs/blob/master/docs/guides/useful-plugins/plugins.data.yaml#L83
Links to the forum which is down now, should point to the repo instead:
https://github.com/Kidev/KZTierMapchooser

**Comment by Sikarii** [comment]
Good catch, should be resolved with #14, I will merge it shortly.

**Comment by Sikarii** [comment]
Resolved with #14, thank you again!
