### ISSUE TITLE
Clarify verifying steps for guides with extensions

### ISSUE THREAD

**Issue by Sikarii** [KZGlobalTeam/docs#7]
When installing an extension prior to anything that relies on the extension, the extension will **not** automatically load.
This should be clarified in the "Confirm this step" when following a step that involves installing an extension.

---
Extensions in SourceMod will not automatically load unless either:
1. An already existing, working plugin needs the extension
2. The extension has an (empty) `.autoload` file in the extensions directory, i.e. `smjansson.autoload`

**Comment by walliski** [comment]
In the case of SteamWorks in the Whitelist guide, we could probably change the instructions to tell them to do `sm exts load SteamWorks` instead. It should output the following message:
```
[SM] Loaded extension SteamWorks.ext.so successfully.
```

There should be an error if it fails to load, for example if the file is in the wrong location, and loading an extension multiple times should not cause issues either.

I could maybe get something together for a PR in the coming days for this.

**Comment by Sikarii** [comment]
Resolved with #10.
